import { ChatInputBox } from "@/components/chat-input";
import { ImageComponent } from "@/components/image-component";
import RecentImages from "@/components/recent-images";
import Image from "next/image";

export default function Home() {
  return (
    <main className="w-full min-h-screen space-y-8 flex justify-center gap-4">
      <div className="space-y-7 p-4 flex-1 fixed left-0">
        <ChatInputBox />
        <ImageComponent alt="Generated by Ai" />
      </div>
      <div className="ml-[500px]">
        <RecentImages />
      </div>
    </main>
  );
}
