import { ChatInputBox } from "@/components/chat-input";
import { ImageComponent } from "@/components/image-component";
import Image from "next/image";

export default function Home() {
  return (
    <main className="max-w-4xl mx-auto p-20 h-screen space-y-8">
      <ChatInputBox />

      <div>
        <ImageComponent alt="Generated by Ai" />
      </div>
    </main>
  );
}
